# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TumblrPhotoFeed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TumblrPhotoFeed
  pod 'AlamofireImage', '~> 3.3'

  target 'TumblrPhotoFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TumblrPhotoFeedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
